version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-apache
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_NAME: naheulbeuk
      DB_USER: root
      DB_PASS: ''
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: naheulbeuk
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
